image test = "test bg.png"
image testguy = "test_guy.png"
image may_base = "HOLY SHIT MAY.png"
image may_alpha = "may_alpha.png"
image test_select_hover = "test_select_hover.png"
image test_select = "test_select.png"